<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="EventLog.fs" />
    <Compile Include="Model.fs" />
    <Compile Include="Commands.fs" />
    <Compile Include="Environment.fs" />
    <Compile Include="Agent.fs" />
    <Compile Include="Scheduler.fs" />
    <Compile Include="Transport.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yession.Domain\Yession.Domain.fsproj" />
  </ItemGroup>

</Project>
