<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Identity.fs" />
    <Compile Include="Events.fs" />
    <Compile Include="Serialization.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Thoth.Json" />
    <PackageReference Include="Thoth.Json.Net" />
  </ItemGroup>

</Project>
