<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Dom.fs" />
    <Compile Include="Routes.fs" />
    <Compile Include="PeerColour.fs" />
    <Compile Include="Model.fs" />
    <Compile Include="DraftSlot.fs" />
    <Compile Include="Connection.fs" />
    <Compile Include="PeerName.fs" />
    <Compile Include="Style.fs" />
    <Compile Include="Icon.fs" />
    <Compile Include="ProseMirror.fs" />
    <Compile Include="Editor.fs" />
    <Compile Include="RichText.fs" />
    <Compile Include="View.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Elmish" />
    <PackageReference Include="Fable.Lit" />
    <PackageReference Include="Ylmish" />
    <PackageReference Include="Fable.Yjs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yession.Domain\Yession.Domain.fsproj" />
  </ItemGroup>

</Project>
